#!/usr/bin/env python3
"""Generate 50 metaphysics questions and assemble final domain file."""

import json
import hashlib
import random

# Load concepts
with open("/Users/jmanning/mapper/data/domains/.working/metaphysics-concepts.json") as f:
    concepts_data = json.load(f)

# Build flat list of (concept_info, difficulty_level)
concept_list = []
for level_key, level_num in [("L1", 1), ("L2", 2), ("L3", 3), ("L4", 4)]:
    for c in concepts_data["concepts"][level_key]:
        concept_list.append((c, level_num))

# All 50 questions - manually crafted
questions_raw = [
    # ===== L1 (13 questions) =====
    {
        "question_text": "What is existence in metaphysics primarily concerned with?",
        "correct_answer": "Whether and in what sense things are or have being",
        "distractors": [
            "How organisms adapt to their environments over time",
            "The mathematical structure underlying physical law descriptions",
            "How individuals form beliefs about the external world"
        ],
        "difficulty": 1,
        "source_article": "Existence",
        "concepts_tested": ["existence"]
    },
    {
        "question_text": "In metaphysics, what does the concept of reality refer to?",
        "correct_answer": "The totality of all things that actually exist, as opposed to mere appearance",
        "distractors": [
            "The set of beliefs a community collectively holds to be justified and true",
            "The mental representations the brain constructs from incoming sensory data",
            "The formal system of logical rules governing valid deductive inference patterns"
        ],
        "difficulty": 1,
        "source_article": "Reality",
        "concepts_tested": ["reality"]
    },
    {
        "question_text": "What is time typically understood as in metaphysics?",
        "correct_answer": "The dimension in which events occur in an ordered succession from past to future",
        "distractors": [
            "A purely subjective illusion generated by the brain's memory consolidation processes",
            "A social construct created by civilizations to coordinate agricultural and economic activity",
            "An emergent property of thermodynamic entropy that exists only in closed systems"
        ],
        "difficulty": 1,
        "source_article": "Time",
        "concepts_tested": ["time"]
    },
    {
        "question_text": "What does the concept of space refer to in metaphysics?",
        "correct_answer": "The boundless three-dimensional extent in which objects have relative position and direction",
        "distractors": [
            "The gravitational field produced by massive bodies that curves light and slows clocks",
            "An abstract mathematical coordinate system used only for modeling physical phenomena",
            "The observable region of the cosmos from which electromagnetic radiation can reach Earth"
        ],
        "difficulty": 1,
        "source_article": "Space",
        "concepts_tested": ["space"]
    },
    {
        "question_text": "What does causation describe in philosophy?",
        "correct_answer": "The relation between a cause and its effect, where one event brings about another",
        "distractors": [
            "The logical entailment between premises and the conclusion of a deductive argument",
            "The statistical correlation observed between two variables in experimental research designs",
            "The temporal ordering of historical events as reconstructed by scholarly investigation methods"
        ],
        "difficulty": 1,
        "source_article": "Causality",
        "concepts_tested": ["causation"]
    },
    {
        "question_text": "What is the mind in philosophy of mind?",
        "correct_answer": "The seat of consciousness, thought, perception, feeling, and imagination in a being",
        "distractors": [
            "The physical brain tissue composed of neurons and glial cells inside the skull",
            "A computational program running on biological hardware that processes sensory input signals",
            "The collection of behavioral dispositions an organism exhibits in response to stimuli"
        ],
        "difficulty": 1,
        "source_article": "Mind",
        "concepts_tested": ["mind"]
    },
    {
        "question_text": "What does the philosophical concept of identity concern?",
        "correct_answer": "What makes an entity the same thing over time or distinguishes it from other entities",
        "distractors": [
            "How social groups assign cultural roles and norms to their individual members",
            "The psychological process by which a person develops a stable sense of self",
            "The logical principle that every well-formed proposition is either true or false"
        ],
        "difficulty": 1,
        "source_article": "Identity (philosophy)",
        "concepts_tested": ["identity"]
    },
    {
        "question_text": "What does the metaphysical concept of change involve?",
        "correct_answer": "A thing acquiring or losing properties it previously had or lacked over time",
        "distractors": [
            "The gradual evolution of species through natural selection across many generations",
            "A shift in scientific paradigms when old theories are replaced by new ones",
            "The transformation of energy from one measurable physical form into another form"
        ],
        "difficulty": 1,
        "source_article": "Change (philosophy)",
        "concepts_tested": ["change"]
    },
    {
        "question_text": "What is free will generally understood to be?",
        "correct_answer": "The capacity of agents to choose and act in a way not wholly determined by prior causes",
        "distractors": [
            "The legal right of citizens to express their opinions without government interference or censorship",
            "The psychological drive that motivates organisms to seek rewards and avoid harmful punishment",
            "The biological ability of the brain to generate random neural firing patterns without stimuli"
        ],
        "difficulty": 1,
        "source_article": "Free will",
        "concepts_tested": ["free will"]
    },
    {
        "question_text": "What is the soul traditionally considered to be in metaphysics?",
        "correct_answer": "An immaterial essence of a person that is distinct from the physical body",
        "distractors": [
            "The pattern of electrical activity in the brain that produces conscious awareness",
            "A metaphor for the totality of a person's character traits and dispositions",
            "The genetic blueprint inherited from parents that determines biological development"
        ],
        "difficulty": 1,
        "source_article": "Soul",
        "concepts_tested": ["soul"]
    },
    {
        "question_text": "In metaphysics, what does the concept of God typically refer to?",
        "correct_answer": "A supreme being conceived as omnipotent, omniscient, and the creator of the universe",
        "distractors": [
            "An abstract principle of cosmic order that governs natural laws without possessing agency",
            "A symbolic representation of humanity's highest moral ideals and collective aspirations",
            "The totality of natural forces that drive evolution and physical change in nature"
        ],
        "difficulty": 1,
        "source_article": "God",
        "concepts_tested": ["God"]
    },
    {
        "question_text": "What does the concept of matter refer to in metaphysics?",
        "correct_answer": "The physical substance that occupies space, has mass, and constitutes the observable world",
        "distractors": [
            "Any entity that can be described using the formal language of mathematical set theory",
            "The information content encoded in the arrangement of fundamental particles in fields",
            "The sensory data received by an observer from which perceptual experience is constructed"
        ],
        "difficulty": 1,
        "source_article": "Matter",
        "concepts_tested": ["matter"]
    },
    {
        "question_text": "What metaphysical question do numbers raise?",
        "correct_answer": "Whether they are abstract objects existing independently or merely human mental constructions",
        "distractors": [
            "Whether arithmetic operations correspond to physical processes occurring inside the brain",
            "Whether different numeral systems lead to fundamentally different mathematical truth values",
            "Whether computers can manipulate numerical symbols without possessing genuine understanding"
        ],
        "difficulty": 1,
        "source_article": "Number",
        "concepts_tested": ["number"]
    },

    # ===== L2 (13 questions) =====
    {
        "question_text": "What is ontology as a branch of metaphysics?",
        "correct_answer": "The study of being that investigates what kinds of entities exist and their categories",
        "distractors": [
            "The analysis of linguistic meaning that examines how words refer to objects in the world",
            "The examination of moral principles that determine which human actions are right or wrong",
            "The investigation of knowledge that asks what conditions must be met for justified belief"
        ],
        "difficulty": 2,
        "source_article": "Ontology",
        "concepts_tested": ["ontology"]
    },
    {
        "question_text": "What does determinism claim about events in the world?",
        "correct_answer": "Every event is necessitated by antecedent causes together with the laws of nature",
        "distractors": [
            "Most events are random but large-scale patterns emerge from statistical averaging processes",
            "Only human actions are causally determined while natural events occur by pure chance",
            "Events are guided by purposeful teleological forces that direct them toward specific goals"
        ],
        "difficulty": 2,
        "source_article": "Determinism",
        "concepts_tested": ["determinism"]
    },
    {
        "question_text": "In substance theory, what is a substance?",
        "correct_answer": "A fundamental entity that exists independently and serves as the bearer of properties",
        "distractors": [
            "Any physical material that can be detected through scientific instruments and measurement devices",
            "A bundle of co-occurring qualities with no underlying subject holding them together",
            "A theoretical posit introduced solely to simplify the mathematical description of phenomena"
        ],
        "difficulty": 2,
        "source_article": "Substance theory",
        "concepts_tested": ["substance"]
    },
    {
        "question_text": "What is a property in the philosophical sense?",
        "correct_answer": "An attribute, quality, or characteristic that an object has or instantiates",
        "distractors": [
            "A legal entitlement giving an owner exclusive control over a physical asset",
            "A measurable quantity that can be assigned a precise numerical value experimentally",
            "A linguistic predicate used in sentences to describe the behavior of subjects"
        ],
        "difficulty": 2,
        "source_article": "Property (philosophy)",
        "concepts_tested": ["property"]
    },
    {
        "question_text": "What does David Lewis's modal realism assert?",
        "correct_answer": "All possible worlds are concrete, really existing entities just as real as the actual world",
        "distractors": [
            "Possible worlds are useful fictions that help analyze modal claims but do not literally exist",
            "Only the actual world exists and modal statements are reducible to facts about language use",
            "Possible worlds are abstract sets of propositions that represent different ways things might be"
        ],
        "difficulty": 2,
        "source_article": "Modal realism",
        "concepts_tested": ["modal realism"]
    },
    {
        "question_text": "What is a possible world in philosophical logic?",
        "correct_answer": "A complete and consistent way things could have been, used to analyze necessity and possibility",
        "distractors": [
            "An alternate physical universe existing in a separate region of the quantum multiverse",
            "A hypothetical scenario constructed for thought experiments that need not be fully consistent",
            "A computer simulation of reality that models how different initial conditions produce different outcomes"
        ],
        "difficulty": 2,
        "source_article": "Possible world",
        "concepts_tested": ["possible world"]
    },
    {
        "question_text": "What does mind-body dualism maintain?",
        "correct_answer": "Mind and body are two fundamentally distinct kinds of substance, neither reducible to the other",
        "distractors": [
            "Mental states are identical to brain states described at a higher level of functional abstraction",
            "Consciousness is an illusion generated by complex information processing in neural networks only",
            "The mind is an emergent property of the body that is fully explicable by physical science alone"
        ],
        "difficulty": 2,
        "source_article": "Mind–body dualism",
        "concepts_tested": ["dualism"]
    },
    {
        "question_text": "What does physicalism assert in metaphysics?",
        "correct_answer": "Everything that exists is physical, or supervenes on and is necessitated by the physical",
        "distractors": [
            "Only entities detectable by current scientific instruments should be admitted into our ontology",
            "The physical sciences provide the best methodology but reality may include non-physical aspects",
            "Matter is the most important substance but mental phenomena form an independent additional category"
        ],
        "difficulty": 2,
        "source_article": "Physicalism",
        "concepts_tested": ["physicalism"]
    },
    {
        "question_text": "What characterizes an abstract object in metaphysics?",
        "correct_answer": "It lacks spatiotemporal location and causal powers, such as numbers and propositions",
        "distractors": [
            "It is a vague or imprecise concept that resists clear definition in formal logical language",
            "It is an unobservable theoretical entity posited by scientific theories to explain observed phenomena",
            "It is a mental image formed by generalizing from particular concrete experiences of objects"
        ],
        "difficulty": 2,
        "source_article": "Abstract and concrete",
        "concepts_tested": ["abstract object"]
    },
    {
        "question_text": "What is an essence in metaphysics?",
        "correct_answer": "The set of necessary properties that make a thing the kind of thing it is",
        "distractors": [
            "The most prominent or salient feature observers typically notice about an object first",
            "A hidden microstructure that science may eventually discover beneath surface level appearances",
            "The purpose or function that an artifact was originally designed and intended to serve"
        ],
        "difficulty": 2,
        "source_article": "Essence",
        "concepts_tested": ["essence"]
    },
    {
        "question_text": "What is the distinction between necessity and contingency in metaphysics?",
        "correct_answer": "Necessary truths could not have been otherwise; contingent truths happen to hold but could have differed",
        "distractors": [
            "Necessary truths are known a priori while contingent truths can only be established through observation",
            "Necessary events are caused by natural laws while contingent events result from free human choices",
            "Necessary propositions are analytic definitions while contingent propositions express synthetic empirical findings"
        ],
        "difficulty": 2,
        "source_article": "Contingency (philosophy)",
        "concepts_tested": ["necessity and contingency"]
    },
    {
        "question_text": "What does the supervenience relation hold between in metaphysics?",
        "correct_answer": "Higher-level properties and lower-level properties, such that no higher-level difference occurs without a lower-level difference",
        "distractors": [
            "Causes and effects in a deterministic system, such that every event has a uniquely sufficient prior cause",
            "Logical premises and conclusions in valid arguments, such that the conclusion cannot be false if premises are true",
            "Moral judgments and natural facts, such that ethical claims are strictly derived from empirical observations alone"
        ],
        "difficulty": 2,
        "source_article": "Supervenience",
        "concepts_tested": ["supervenience"]
    },
    {
        "question_text": "What does nominalism deny in metaphysics?",
        "correct_answer": "The existence of universals or abstract objects as mind-independent entities in reality",
        "distractors": [
            "The existence of particular concrete objects located in space and time around us",
            "The possibility of gaining knowledge about the external world through sense experience",
            "The meaningfulness of general terms and predicates used in everyday natural language"
        ],
        "difficulty": 2,
        "source_article": "Nominalism",
        "concepts_tested": ["nominalism"]
    },

    # ===== L3 (12 questions) =====
    {
        "question_text": "What is the problem of universals in metaphysics?",
        "correct_answer": "Whether properties shared by multiple objects exist as real universals or only as names and resemblances",
        "distractors": [
            "Whether the laws of logic apply universally across all possible worlds or only within the actual world",
            "Whether moral principles hold for all cultures or are relative to particular social frameworks and norms",
            "Whether scientific theories describe reality as it truly is or merely predict observable experimental outcomes"
        ],
        "difficulty": 3,
        "source_article": "Problem of universals",
        "concepts_tested": ["problem of universals"]
    },
    {
        "question_text": "What is the central question of personal identity over time?",
        "correct_answer": "What makes a person at one time the same person at a later time despite physical and psychological changes",
        "distractors": [
            "How individuals develop a unique personality through socialization and cultural influences during childhood years",
            "Whether human beings possess an immortal soul that survives the biological death of the physical body",
            "How memory consolidation during sleep creates a continuous narrative that the brain interprets as selfhood"
        ],
        "difficulty": 3,
        "source_article": "Personal identity",
        "concepts_tested": ["personal identity over time"]
    },
    {
        "question_text": "What position does compatibilism take on free will and determinism?",
        "correct_answer": "Free will is compatible with determinism because freedom requires acting on one's own desires without external compulsion",
        "distractors": [
            "Free will is impossible because every human action is entirely determined by prior causes and physical laws",
            "Free will requires genuine indeterminism at the quantum level to open space for undetermined choices",
            "Free will and determinism are both false because events occur through a mix of chance and necessity"
        ],
        "difficulty": 3,
        "source_article": "Compatibilism",
        "concepts_tested": ["compatibilism"]
    },
    {
        "question_text": "What does mereology study?",
        "correct_answer": "The formal relations between parts and wholes, including when parts compose a further object",
        "distractors": [
            "The logical structure of mathematical proofs and the foundations of axiomatic set theory",
            "The classification of organisms into hierarchical taxonomic groups based on shared characteristics",
            "The spatial geometry of physical objects and how their shapes determine mechanical interactions"
        ],
        "difficulty": 3,
        "source_article": "Mereology",
        "concepts_tested": ["mereology"]
    },
    {
        "question_text": "What does eternalism assert about the existence of past and future entities?",
        "correct_answer": "Past, present, and future entities all equally exist in a four-dimensional block universe",
        "distractors": [
            "Only the present moment exists and past and future entities are merely conceptual abstractions",
            "The past exists as a fixed record but the future is genuinely open and ontologically indeterminate",
            "Time is cyclical so all events recur eternally and past and future are ultimately identical"
        ],
        "difficulty": 3,
        "source_article": "Eternalism (philosophy of time)",
        "concepts_tested": ["eternalism"]
    },
    {
        "question_text": "What does presentism hold about temporal existence?",
        "correct_answer": "Only presently existing entities are real; past and future objects do not exist",
        "distractors": [
            "All temporal moments exist equally and the present has no special ontological status",
            "The present is an illusion created by consciousness and only the past truly exists",
            "Past and future exist but in a diminished or less concrete mode than present things"
        ],
        "difficulty": 3,
        "source_article": "Presentism (philosophy of time)",
        "concepts_tested": ["presentism"]
    },
    {
        "question_text": "What does bundle theory claim about objects?",
        "correct_answer": "Objects are nothing more than bundles of co-occurring properties with no underlying bare particular",
        "distractors": [
            "Objects are constituted by a single indivisible substance that persists through all qualitative changes",
            "Objects are mental constructions that the mind assembles from discrete unconnected sense impressions",
            "Objects are defined entirely by their causal and relational roles within a larger structural network"
        ],
        "difficulty": 3,
        "source_article": "Bundle theory",
        "concepts_tested": ["bundle theory"]
    },
    {
        "question_text": "What does the principle of causal closure of the physical state?",
        "correct_answer": "Every physical effect has a sufficient physical cause, leaving no causal gaps for non-physical intervention",
        "distractors": [
            "Every causal chain must terminate in a first uncaused cause that grounds the entire sequence",
            "Physical systems are isolated from outside influence and cannot receive energy from external sources",
            "All physical laws are deterministic and no genuinely random events occur at any fundamental level"
        ],
        "difficulty": 3,
        "source_article": "Causal closure",
        "concepts_tested": ["causal closure"]
    },
    {
        "question_text": "What does emergence refer to in metaphysics?",
        "correct_answer": "The arising of novel higher-level properties from lower-level components that are not straightforwardly reducible to them",
        "distractors": [
            "The historical process by which new scientific disciplines branch off from older established research fields",
            "The developmental unfolding of an organism's traits from the genetic information encoded in its DNA",
            "The sudden appearance of order in chaotic systems when a critical threshold parameter value is crossed"
        ],
        "difficulty": 3,
        "source_article": "Emergence",
        "concepts_tested": ["emergence"]
    },
    {
        "question_text": "What are natural kinds in metaphysics?",
        "correct_answer": "Categories that reflect genuine divisions in nature, such as chemical elements, rather than arbitrary human groupings",
        "distractors": [
            "The innate cognitive categories that the human mind uses to organize all sensory experience automatically",
            "The fundamental particle types described by the standard model of contemporary high-energy particle physics",
            "The biological species recognized by taxonomists that can interbreed and produce viable fertile offspring"
        ],
        "difficulty": 3,
        "source_article": "Natural kind",
        "concepts_tested": ["natural kinds"]
    },
    {
        "question_text": "What is debated about laws of nature in metaphysics?",
        "correct_answer": "Whether they are mere regularities in the Humean sense or reflect necessary connections between properties",
        "distractors": [
            "Whether they were established by a divine lawgiver or arose spontaneously from physical processes",
            "Whether they apply uniformly throughout the universe or vary across different spatial regions",
            "Whether they can be fully expressed in mathematical language or require qualitative verbal description"
        ],
        "difficulty": 3,
        "source_article": "Laws of nature",
        "concepts_tested": ["laws of nature"]
    },
    {
        "question_text": "What does trope theory claim about properties?",
        "correct_answer": "Properties are particular, non-repeatable instances rather than universals shared identically across objects",
        "distractors": [
            "Properties are abstract universals existing in a Platonic realm independent of any particular objects",
            "Properties are linguistic constructs that have no ontological status beyond the words describing them",
            "Properties are relational structures defined entirely by the causal roles they play in physical laws"
        ],
        "difficulty": 3,
        "source_article": "Trope theory",
        "concepts_tested": ["trope theory"]
    },

    # ===== L4 (12 questions) =====
    {
        "question_text": "What is the grounding relation in contemporary metaphysics?",
        "correct_answer": "A non-causal relation of metaphysical priority in which one fact obtains in virtue of another more fundamental fact",
        "distractors": [
            "A causal dependence relation in which earlier events in a temporal sequence produce later events necessarily",
            "A logical entailment relation in which the truth of one proposition deductively guarantees another's truth value",
            "A supervenience relation in which higher-level descriptions are simply shorthand for complex lower-level physical facts"
        ],
        "difficulty": 4,
        "source_article": "Grounding (metaphysics)",
        "concepts_tested": ["grounding relation"]
    },
    {
        "question_text": "What does truthmaker theory require for every true proposition?",
        "correct_answer": "An entity in the world whose existence necessitates the truth of that proposition",
        "distractors": [
            "A coherent set of beliefs within which the proposition fits without generating contradictions",
            "An empirical verification procedure that could in principle confirm the proposition's truth value",
            "A competent language user who asserts the proposition sincerely in appropriate conversational contexts"
        ],
        "difficulty": 4,
        "source_article": "Truthmaker theory",
        "concepts_tested": ["truthmaker theory"]
    },
    {
        "question_text": "How does four-dimensionalism explain an object's persistence through time?",
        "correct_answer": "An object is a four-dimensional entity extended in time with distinct temporal parts at each moment",
        "distractors": [
            "An object is wholly present at each moment of its existence without any temporal segmentation",
            "An object persists by being continuously recreated at each instant by the laws of nature",
            "An object endures by maintaining a permanent essential core while its accidental properties change"
        ],
        "difficulty": 4,
        "source_article": "Four-dimensionalism",
        "concepts_tested": ["four-dimensionalism"]
    },
    {
        "question_text": "What does endurantism claim about how objects persist through time?",
        "correct_answer": "Objects are wholly present at every moment of their existence rather than having distinct temporal parts",
        "distractors": [
            "Objects are four-dimensional worms extended across time with a different temporal part at each instant",
            "Objects persist only as a series of momentary stages connected by causal and similarity relations",
            "Objects endure by retaining a fixed spatial location while undergoing continuous qualitative internal change"
        ],
        "difficulty": 4,
        "source_article": "Endurantism",
        "concepts_tested": ["endurantism"]
    },
    {
        "question_text": "What does haecceitism maintain about individual identity?",
        "correct_answer": "Individuals possess a primitive thisness or haecceity not reducible to their qualitative properties alone",
        "distractors": [
            "Individuals are entirely constituted by their qualitative properties and relations to other existing entities",
            "Individual identity is determined solely by spatiotemporal continuity through the actual physical world",
            "Individuals are identical across possible worlds if and only if they share all essential properties"
        ],
        "difficulty": 4,
        "source_article": "Haecceity",
        "concepts_tested": ["haecceitism"]
    },
    {
        "question_text": "What does ontic structural realism claim is most fundamental in reality?",
        "correct_answer": "Structures and relations are ontologically fundamental, with objects being derivative or eliminable",
        "distractors": [
            "Individual objects with intrinsic properties are fundamental and relations are secondary to them",
            "Observable phenomena are fundamental and theoretical structures are merely useful predictive instruments",
            "Mathematical equations are the ultimate reality and physical objects are their concrete instantiations"
        ],
        "difficulty": 4,
        "source_article": "Structural realism",
        "concepts_tested": ["ontic structural realism"]
    },
    {
        "question_text": "What is Humean supervenience as defended by David Lewis?",
        "correct_answer": "All facts about the world supervene on the spatiotemporal distribution of local intrinsic qualities of point-sized things",
        "distractors": [
            "All causal relations are reducible to observed constant conjunctions without any necessary connections between events",
            "All modal truths are grounded in the concrete existence of a plurality of equally real possible worlds",
            "All mental properties supervene on physical brain states such that no mental difference occurs without a physical one"
        ],
        "difficulty": 4,
        "source_article": "Humean supervenience",
        "concepts_tested": ["Humean supervenience"]
    },
    {
        "question_text": "What does dialetheism claim about contradictions?",
        "correct_answer": "Some contradictions are true; there exist propositions that are both true and false simultaneously",
        "distractors": [
            "All contradictions are meaningless and cannot express any genuine propositional content whatsoever",
            "Contradictions indicate errors in reasoning and must be resolved by revising one of the premises",
            "Apparent contradictions always dissolve upon closer analysis through disambiguating the relevant terms used"
        ],
        "difficulty": 4,
        "source_article": "Dialetheism",
        "concepts_tested": ["dialetheism"]
    },
    {
        "question_text": "What does mereological nihilism assert about composite objects?",
        "correct_answer": "Composite objects do not exist; only mereological simples arranged in various ways are real",
        "distractors": [
            "Every collection of objects automatically composes a further object regardless of their arrangement",
            "Composite objects exist but are ontologically reducible to the sum of their individual parts",
            "Only living organisms are genuine composite objects while artifacts are merely simples arranged conveniently"
        ],
        "difficulty": 4,
        "source_article": "Mereological nihilism",
        "concepts_tested": ["mereological nihilism"]
    },
    {
        "question_text": "How does Lewis's counterpart theory analyze de re modal claims?",
        "correct_answer": "An individual's modal properties are determined by the properties of its counterparts in other possible worlds",
        "distractors": [
            "An individual literally exists in multiple possible worlds and its modal properties reflect those trans-world presences",
            "Modal properties are intrinsic features of individuals that can be known through rational intuition alone",
            "De re modal claims are meaningless because individuals cannot be identified across distinct possible world contexts"
        ],
        "difficulty": 4,
        "source_article": "Counterpart theory",
        "concepts_tested": ["counterpart theory"]
    },
    {
        "question_text": "What does causal set theory propose about the fundamental nature of spacetime?",
        "correct_answer": "Spacetime is fundamentally a discrete partially ordered set of events related by causality, not a continuum",
        "distractors": [
            "Spacetime is a smooth continuous manifold whose curvature is determined by the distribution of mass and energy",
            "Spacetime is an emergent illusion arising from quantum entanglement between particles on a holographic boundary",
            "Spacetime is a static four-dimensional block where the flow of time is a subjective psychological phenomenon"
        ],
        "difficulty": 4,
        "source_article": "Causal sets",
        "concepts_tested": ["causal set theory"]
    },
    {
        "question_text": "What does Jonathan Schaffer's priority monism claim about fundamentality?",
        "correct_answer": "The cosmos as a whole is the one fundamental entity, and all proper parts are ontologically derivative",
        "distractors": [
            "There is exactly one kind of substance in reality, and all apparent diversity reduces to variations of it",
            "The most fundamental entities are the smallest possible mereological simples from which everything is composed",
            "All objects are equally fundamental and none has ontological priority over any other existing entity"
        ],
        "difficulty": 4,
        "source_article": "Priority monism",
        "concepts_tested": ["priority monism"]
    },
]

print(f"Total questions generated: {len(questions_raw)}")
assert len(questions_raw) == 50, f"Expected 50 questions, got {len(questions_raw)}"

# Verify concept coverage
concepts_in_questions = [q["concepts_tested"][0] for q in questions_raw]
concepts_in_file = []
for level_key in ["L1", "L2", "L3", "L4"]:
    for c in concepts_data["concepts"][level_key]:
        concepts_in_file.append(c["concept"])

print(f"Concepts in file: {len(concepts_in_file)}")
print(f"Concepts in questions: {len(concepts_in_questions)}")

# Check each concept is covered
for c in concepts_in_file:
    if c not in concepts_in_questions:
        print(f"  MISSING concept: {c}")

# Save working file
with open("/Users/jmanning/mapper/data/domains/.working/metaphysics-questions.json", "w") as f:
    json.dump(questions_raw, f, indent=2)
print("Saved working questions file.")

# Now assemble the final domain file
# Load existing domain structure
with open("/Users/jmanning/mapper/data/domains/metaphysics.json") as f:
    domain_data = json.load(f)

# Generate IDs and assign answer slots
random.seed(42)
slots = ["A", "B", "C", "D"]

final_questions = []
for q in questions_raw:
    # Generate ID: first 16 hex chars of SHA-256 of question_text
    q_hash = hashlib.sha256(q["question_text"].encode("utf-8")).hexdigest()[:16]

    # Randomize answer slot
    random.shuffle(slots)
    correct_slot = slots[0]

    # Build options dict
    options = {}
    distractor_idx = 0
    for slot in sorted(["A", "B", "C", "D"]):
        if slot == correct_slot:
            options[slot] = q["correct_answer"]
        else:
            options[slot] = q["distractors"][distractor_idx]
            distractor_idx += 1

    final_q = {
        "id": q_hash,
        "question_text": q["question_text"],
        "options": options,
        "correct_answer": correct_slot,
        "difficulty": q["difficulty"],
        "source_article": q["source_article"],
        "domain_ids": q.get("domain_ids", ["metaphysics"]),
        "concepts_tested": q["concepts_tested"]
    }
    final_questions.append(final_q)

domain_data["questions"] = final_questions

# Write final file
with open("/Users/jmanning/mapper/data/domains/metaphysics.json", "w") as f:
    json.dump(domain_data, f, indent=2)

print(f"Final domain file written with {len(final_questions)} questions.")

# Print summary
difficulty_counts = {}
for q in final_questions:
    d = q["difficulty"]
    difficulty_counts[d] = difficulty_counts.get(d, 0) + 1
print(f"Difficulty distribution: {difficulty_counts}")

# Verify ID uniqueness
ids = [q["id"] for q in final_questions]
assert len(ids) == len(set(ids)), "Duplicate IDs found!"
print("All IDs are unique.")

# Verify answer distribution
answer_counts = {}
for q in final_questions:
    a = q["correct_answer"]
    answer_counts[a] = answer_counts.get(a, 0) + 1
print(f"Answer distribution: {answer_counts}")

# Print first 3 questions as sample
print("\n=== SAMPLE QUESTIONS ===")
for q in final_questions[:3]:
    print(f"\nID: {q['id']}")
    print(f"Q: {q['question_text']}")
    for slot in ["A", "B", "C", "D"]:
        marker = " *" if slot == q["correct_answer"] else ""
        print(f"  {slot}: {q['options'][slot]}{marker}")
    print(f"Difficulty: {q['difficulty']}, Concept: {q['concepts_tested']}")
